[phases.setup]
aptPks = [
    'libnss3',
    'libatk1.0-0',
    'libatk-bridge2.0-0',
    'libgdk-pixbuf2.0-0',
    'libgtk-3-0',
    'libgbm-dev',
    'libxss1',
    'libasound2',
    'libgobject-2.0-0'
]